[workspace] 
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
  "bioconda"
]
platforms = ["linux-64", "osx-arm64", "osx-64"]
preview = ["pixi-build"]
readme = "README.md"


[dependencies] 
coidb = { path = "." }

[package] 
name = "coidb"
version = "0.1.0"

[package.build] 
backend = { name = "pixi-build-python", version = "0.1.*" }

[package.host-dependencies] 
hatchling = "==1.26.3"

[package.run-dependencies]
snk-cli = "==0.7.2"
snakemake = ">=9"
python = "*"
vsearch = "*"
polars = "*"
seqkit = "*"
snakemake-executor-plugin-slurm = "*"

[tasks]
test = "pytest tests/test.py"