[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
  "bioconda",
]
platforms = ["linux-64", "osx-arm64", "osx-64"]
preview = ["pixi-build"]
readme = "README.md"


[dependencies]
coidb = { path = "." }
black = ">=25.12.0,<26"

[package]
name = "coidb"
version = "0.6.0"

[package.build]
backend = { name = "pixi-build-python", version = "0.4.*" }

[package.host-dependencies]
hatchling = "==1.27.0"

[package.run-dependencies]
snk-cli = "==0.7.2"
snakemake = ">=9"
python = "*"
vsearch = "*"
polars = "*"
seqkit = "*"
snakemake-executor-plugin-slurm = "*"
pygbif = "*"
tqdm = ">=4.67.1,<5"
graphviz = ">=14.0.4,<15"

[tasks]
test = "pytest tests/test.py"
