default-resources: 
  slurm_account: <your-slurm-account>
  slurm_partition: <your-slurm-partition>
  runtime: 240
  cpus_per_task: 1
  mem_mb: 6000


set-resources:
  calculate_consensus:
    mem_mb: 60000
  add_to_vsearch:
    mem_mb: 3552

set-threads:
  calculate_consensus: 10

printshellcmds: False
local-cores: 1
keep-going: True
rerun-triggers: mtime
rerun-incomplete: True
local-cores: 1
jobs: 100
latency-wait: 5
executor: slurm