default-resources: 
  slurm_account: <your-slurm-account>
  slurm_partition: <your-slurm-partition>
  runtime: 30
  mem_mb: 2000


set-resources:
  filter:
    mem_mb: 20000
  fill_missing:
    mem_mb: 4000
  calculate_consensus:
    mem_mb: 20000
  vsearch:
    runtime: 30
  add_to_vsearch:
    mem_mb: 4000
  parse_backbone:
    mem_mb: 4000

set-threads:
  filter: 10
  calculate_consensus: 10

printshellcmds: False
local-cores: 1
keep-going: True
rerun-triggers: mtime
rerun-incomplete: True
local-cores: 1
jobs: 100
latency-wait: 5
executor: slurm