default-resources: 
  slurm_partition: shared
  runtime: 60
  mem_mb: 1776


set-resources:
  filter:
    mem_mb: 26640
  multi_record_bins:
    mem_mb: 26640
  fill_missing:
    mem_mb: 7104
  fix_nonunique:
    mem_mb: 7104
  calculate_consensus:
    mem_mb: 14208
  vsearch:
    runtime: 600
  add_to_vsearch:
    mem_mb: 3552
  parse_backbone:
    mem_mb: 3552

set-threads:
  filter: 15
  multi_record_bins: 15
  calculate_consensus: 8

printshellcmds: False
local-cores: 1
keep-going: True
rerun-triggers: mtime
rerun-incomplete: True
local-cores: 1
jobs: 100
latency-wait: 5
executor: slurm